modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="caffeinated"
version="${file.jarVersion}"
displayName="Caffeinated"
logoFile="icon.png"
credits="Ported by ExDrill"
authors="Chikorita Lover"

description='''
Adds new coffee shrubs and items that provide a new caffeine effect.
'''

[[dependencies.caffeinated]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.caffeinated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
